# Markdownlint configuration for Luxe project
# https://github.com/DavidAnson/markdownlint/blob/main/doc/RULES.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Maximum line length
  line_length: 120
  # Number of characters for a code block tab
  code_block_line_length: 120
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Allow headings to have the same content if they're under different parents
  siblings_only: true

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  # No trailing spaces for line breaks
  br_spaces: 0
  # No trailing spaces in empty list items
  list_item_empty_lines: false
  # Strict mode - no trailing spaces at all
  strict: true

# MD032/no-blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

whitespace: false
