---
name: Delete Old Images

on:
  schedule:
    # Run every Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old bazaar package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'bazaar'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'

      - name: Delete old destined package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'destined'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'
